### ISSUE TITLE
Error with test

### ISSUE THREAD

**Issue by mike-lawrence** [yati-sagade/opencv-ndarray-conversion#1]
I'm getting the following error during make:

```
ld: can't map file, errno=22 file '/usr/local/Cellar/opencv/2.4.9/lib/' for architecture x86_64
```

To even get that far I had to edit the Makefile: https://gist.github.com/mike-lawrence/b1da52cdba1521014cc3

Any idea what's up?

**Comment by yati-sagade** [comment]
I think you're missing an `-L` before `$(OPENCV_LIB)` - It should be `-L$(OPENCV_LIB)` to start with :)

EDIT: I'm sorry, my bad. `OPENCV_LIB` comes from `pkg-config` - so a separate `-L` is _not_ needed.

**Comment by mike-lawrence** [comment]
I ended up getting this working afterall, so closing. (I can't actually recall what I did to fix it, sorry; did a lot of re-installing and then playing with cmake...)

**Comment by yati-sagade** [comment]
Haha. From what I found on the web, many people who compiled OpenCV with CUDA on OS X had this problem.
