### ISSUE TITLE
Handling grayscale images

### ISSUE THREAD

**Issue by mike-lawrence** [yati-sagade/opencv-ndarray-conversion#2]
Any idea how to tweak your code to handle grayscale images? Currently I get a "MemoryError" if I pass one.

**Comment by yati-sagade** [comment]
AFAIK it works out of the box. I've added some extra tests - check them out. Also, can you post the code that's failing for you?

**Comment by mike-lawrence** [comment]
Ah, I had been creating my grayscale images by simply grabbing one channel (ex. `img = img[:,:,0]`) but now see that if I do `img = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)`, I no longer get the memory error.
